[default]
# Dev mode
DEBUG = false
# Pathes
DB_PATH = 'data/db'
LOG_PATH = 'logs/bot.log'
# Internal parameters
DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'
# Notification message
TIMEZONE = 'US/Eastern'
ADMINS = [ '@PLACEHOLDER' ]

[production]
DEBUG = false
TOKEN = 'SECRET_PLACEHOLDER'
CHANNEL_USERNAME = 'PLACEHOLDER'
CHAT_ID = 'PLACEHOLDER'
CONVERSATION_TIMEOUT = 86400            # 24 hours (in seconds)
SLOW_MODE = 3600                        # 1 hour (in seconds)
SCHEDULE_IMAGE = 'PLACEHOLDER'

[development]
DEBUG = true
TOKEN = 'SECRET_PLACEHOLDER'
CHANNEL_USERNAME = 'PLACEHOLDER'
CHAT_ID = 'PLACEHOLDER'
CONVERSATION_TIMEOUT = 10               # 10 seconds
SLOW_MODE = 10                          # 10 seconds
SCHEDULE_IMAGE = 'https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_(test_image).png'